name: Node.js Hello Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Print Hello
        run: echo "Hello from @RishabhRanjanmiw

